### ISSUE TITLE
GNC Requirements Definition

### ISSUE THREAD

**Issue by austrian-code-wizard** [stanford-ssi/IBM-Satellite#3]

**Comment by aleclessing** [comment]
-Depending on the version of Pycubed we use, the IMU interface will likely already be high enough level code that GNC will handle it directly
-Magnet-torquer control will essentially amount to an numberical output specifying the amount of current to send to each magnet-torquer. Most likely it will work for software team to make some sort of class or function that allows GNC team code to set the current to each magnet-torquer and software will handle how that fits into the main code.
