### ISSUE TITLE
Make all components parametric

### ISSUE THREAD

**Issue by ConnorCremers** [stanford-ssi/IBM-Satellite#38]
The primary structure has been restored to it's fully parametric (at least with respect to rail distances) form. Several of the secondary structures (or all of them rather...) fail to scale appropriately. We should fix this moving forward.

I think it makes most sense for everybody to tweak their own components, so I'm assigning all structures members.

Since this mostly means getting thigns to interface correctly with the inside of the rails, I would take a look at E_frame_top_3U_v2 for some context.

**Comment by polygnomial** [comment]
Can you switch the repo please @ConnorCremers?
