### ISSUE TITLE
Research PyCubed

### ISSUE THREAD

**Issue by austrian-code-wizard** [stanford-ssi/IBM-Satellite#7]

**Comment by lgnashold** [comment]
PyCubed basically provides us an easy platform to use most of the main functionality of the satellite and provides some structure for increased functionality. Out of the box, it comes with an IMU, SSD, slots for two radios, slots for four payloads, 2-4 burn wires (depending on v2 or v4) and a GPS module. It does not have any sort of GNC capabilities, which will be controlled by the RaspPi (or alternative) anyway. 
PyCubed uses the Circuit Python framework, which means you can plug it in and edit it as simply as editing a file on a flash drive. It also uses the circuit python drivers and bootloader (see the firmware repo). The CircuitPython framework gives us a couple of other really nice things, like the REPL (basically run code in real time). 
In each file in the lib folder is a library, which you can read as a normal python file. The main library is called pycubed.py, and it abstracts some of the core satellite functionality (initializing the main components). Writing code to use these is really simple. It pretty much just looks like python, except we might not have access to all the same libraries as in normal python. For example, getting the temperature from the IMU is just one line of code. 
When we want to extend the functionality beyond the base components, it will involve writing more low-level firmware and custom libraries to interact with them.
